name: extended_video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web. Supports caching on Android and iOS.
repository: https://github.com/XuanTung95/packages/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/XuanTung95/packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.8.6

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.6"

flutter:
  plugin:
    platforms:
      android:
        default_package: extended_video_player_android
      ios:
        default_package: extended_video_player_avfoundation
      macos:
        default_package: extended_video_player_avfoundation
      web:
        default_package: extended_video_player_web

dependencies:
  extended_video_player_android: ^2.3.5
  extended_video_player_avfoundation: ^2.5.6
  extended_video_player_platform_interface: ">=6.1.0 <7.0.0"
  extended_video_player_web: ^2.0.0
  flutter:
    sdk: flutter
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
# dependency_overrides:
#   {video_player_android: {path: ../../video_player/video_player_android}, video_player_platform_interface: {path: ../../video_player/video_player_platform_interface}}
topics:
  - video
  - video-player
