name: extended_video_player_avfoundation
description: iOS and macOS implementation of the video_player plugin.
repository: https://github.com/XuanTung95/packages/tree/main/packages/video_player/video_player_avfoundation
issue_tracker: https://github.com/XuanTung95/packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.6.1

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

flutter:
  plugin:
    implements: extended_video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FVPVideoPlayerPlugin
        sharedDarwinSource: true
      macos:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FVPVideoPlayerPlugin
        sharedDarwinSource: true

dependencies:
  extended_video_player_platform_interface: ">=6.1.0 <7.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^18.0.0

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
# dependency_overrides:
#    {video_player_platform_interface: {path: ../../video_player/video_player_platform_interface}}
topics:
  - video
  - video-player
